### ISSUE TITLE
Automatically Import Missing Type

### ISSUE THREAD

**Issue by dustinlacewell** [ananthakumaran/tide#373] opened 2020-04-22 21:12 UTC
Would it be possible to have a feature which would automatically add an import for the missing type at point? So you start writing some code and you name a type you haven't imported yet, executing this command would either import the only candidates, or show you a list of multiple candidates.

**Comment by josteink** [comment] 2020-04-23 09:32
This is already handled by `tide-fix`.

**Comment by dustinlacewell** [comment] 2020-04-25 15:25
It just says "No code-fixes available" when I put the point over an unimported type.

**Comment by lddubeau** [comment] 2020-04-25 15:46
It is handled by `tide-fix`. Ultimately `tide-fix` is limited by what `tsserver` provides. One particular limitation is that if fix to resolve an undefined type would be to import a file that *has never been imported* in the files known to `tsserver`, then `tsserver` won't suggest a fix. In other words, `tsserver` if importing from file X would fix the issue, `tsserver` will suggest importing X if and only if X is already known to `tsserver`.

@dustinlacewell make sure you're not in the situation I describe above. If you are not, and there's still a problem, then the only way to move this issue forward is to provide a MCVE. Ultimately though `tide`'s responsibility is very limited. If `tide-fix` fails to automatically offer an import for a specific case, chances are that the problem is in `tsserver` and needs to be fixed there.

**Comment by ananthakumaran** [comment] 2020-05-23 13:53
Closing this, as there is no actionable item on the tide.

**Closed by ananthakumaran** 2020-05-23 13:53 UTC
