### ISSUE TITLE
Organize imports with multiple lines

### ISSUE THREAD

**Issue by JacksonGariety** [ananthakumaran/tide#364] opened 2020-02-28 05:47 UTC
When submitting issues to this project, please include the following information.

## Checklist

- [x] I have searched both open and closed issues and cannot find a duplicate.
- [x] I can [reproduce the problem](https://github.com/ananthakumaran/tide/wiki/Explanations-about-the-Issue-Reporting-Checklist#use-the-latest-version-of-the-relevant-packages) with the latest version of the relevant packages.
- [x] The problem still occurs after I issued [`M-x tide-restart-server`](https://github.com/ananthakumaran/tide/wiki/Explanations-about-the-Issue-Reporting-Checklist#try-m-x-tide-restart-server) in the buffer where I had the problem.
- [x] I verified that the version and the configuration file path reported by [`M-x tide-verify-setup`](https://github.com/ananthakumaran/tide/wiki/Explanations-about-the-Issue-Reporting-Checklist#check-the-information-reported-by-m-x-tide-verify-setup) are correct.
- [x] If [tide *is reporting*](https://github.com/ananthakumaran/tide/wiki/Explanations-about-the-Issue-Reporting-Checklist#the-behavior-of-cli-tools-agrees-with-your-expectations) an error or warning I think *should not be reported*, I can run `tsc` (and `tslint`, if applicable) without the error or warning I'm seeing in tide.
- [x] If [tide is *not reporting*](https://github.com/ananthakumaran/tide/wiki/Explanations-about-the-Issue-Reporting-Checklist#the-behavior-of-cli-tools-agrees-with-your-expectations) an error or warning I think *should be reported*, `tsc` (or `tslint`, if applicable) reports the error or warning I was expecting to see.
- [x] I am [positive](https://github.com/ananthakumaran/tide/wiki/Explanations-about-the-Issue-Reporting-Checklist#how-to-determine-which-project-the-problem-belongs-to) the problem does not belong to `typescript-mode` or `tsserver`.

## Relevant Version Numbers

- Tide: 3.7.4
- TypeScript: 3.8.2
- Emacs: 26.3

(The list above is minimal. Make sure to include any other version numbers relevant to your report.)

## Steps to Reproduce the Bug

Run "tide-organize-files" in a file with a multi-line import statement.

For example

```javascript
import {
  foo,
  bar,
  raz,
  zup,
}
```

## Expected Behavior

Tide should automatically insert line breaks if more than X number of packages are being imported.

It looks like eslint throws the "object curly newline" error if an import statement has more than 2 imports: https://github.com/eslint/eslint/search?q=minProperties&unscoped_q=minProperties

## Actual Behavior

Tide clobbers all manually-inserted line breaks.

**Comment by josteink** [comment] 2020-02-28 06:18
I'm think this might be the work of `tsserver` and not `tide` (ref your latest checkpoint on the list).

Can you reproduce the same behaviour in VSCode? Or does it behave differently?

**Comment by lddubeau** [comment] 2020-02-28 14:12
From the submission:

> Run "tide-organize-files"

There's no such thing as `tide-organize-files`. Probably the submitter meant `tide-organize-imports`.

But even then, I'm absolutely sure that the undesirable behavior is the work of `tsserver`, not `tide`. I have some unreleased alpha code that adds dependency sorting to `tide` itself. Absent this code, tide *itself* does not do dependency sorting. When `tide-organize-imports` runs, the work is delegated to `tsserver`. If `tsserver` does not behave the way it should, that's an issue to be filed with `tsserver`.

Consequently, I'm closing this because the problem does not lie with tide. As usual, if I am wrong and a case can be made for reopening, we'll reopen.

----

For import sorting, I've gone through a bunch of methods to get results I liked. One thing I've never done is rely on `tide-organize-imports` because I've never liked what `tsserver` does. For a while I was running my alpha sorting code but I no longer use it. For all new TS projects now, my default linting setup is to use `eslint` for JS and TS code. I use [this plugin](https://github.com/lydell/eslint-plugin-simple-import-sort), with the following configuration in [this file](https://github.com/lddubeau/eslint-config-lddubeau-base/blob/master/common.js). The relevant parts are [this one](https://github.com/lddubeau/eslint-config-lddubeau-base/blob/9eeaa67199d37011d31e044a0cf8915af71cbf87/common.js#L12-L27) [this one](https://github.com/lddubeau/eslint-config-lddubeau-base/blob/9eeaa67199d37011d31e044a0cf8915af71cbf87/common.js#L35), and [this one](https://github.com/lddubeau/eslint-config-lddubeau-base/blob/9eeaa67199d37011d31e044a0cf8915af71cbf87/common.js#L109-L122). Then running `eslint --fix` fixes all sorting issues.

The code for detecting a monorepo in the configuration above is brittle, but for the projects I work on it is brittle in a way that doesn't matter. (False positives happen, but they ultimately make no difference.)

**Closed by lddubeau** 2020-02-28 14:12 UTC
