### ISSUE TITLE
 Add parentheses to the method

### ISSUE THREAD

**Issue by taigacute** [ananthakumaran/tide#335] opened 2019-09-17 14:56 UTC
When submitting issues to this project, please include the following information.

## Checklist

- [X ] I have searched both open and closed issues and cannot find a duplicate.
- [X ] I can [reproduce the problem](https://github.com/ananthakumaran/tide/wiki/Explanations-about-the-Issue-Reporting-Checklist#use-the-latest-version-of-the-relevant-packages) with the latest version of the relevant packages.
- [ X] The problem still occurs after I issued [`M-x tide-restart-server`](https://github.com/ananthakumaran/tide/wiki/Explanations-about-the-Issue-Reporting-Checklist#try-m-x-tide-restart-server) in the buffer where I had the problem.
- [ ] I verified that the version and the configuration file path reported by [`M-x tide-verify-setup`](https://github.com/ananthakumaran/tide/wiki/Explanations-about-the-Issue-Reporting-Checklist#check-the-information-reported-by-m-x-tide-verify-setup) are correct.
- [ ] If [tide *is reporting*](https://github.com/ananthakumaran/tide/wiki/Explanations-about-the-Issue-Reporting-Checklist#the-behavior-of-cli-tools-agrees-with-your-expectations) an error or warning I think *should not be reported*, I can run `tsc` (and `tslint`, if applicable) without the error or warning I'm seeing in tide.
- [ ] If [tide is *not reporting*](https://github.com/ananthakumaran/tide/wiki/Explanations-about-the-Issue-Reporting-Checklist#the-behavior-of-cli-tools-agrees-with-your-expectations) an error or warning I think *should be reported*, `tsc` (or `tslint`, if applicable) reports the error or warning I was expecting to see.
- [ ] I am [positive](https://github.com/ananthakumaran/tide/wiki/Explanations-about-the-Issue-Reporting-Checklist#how-to-determine-which-project-the-problem-belongs-to) the problem does not belong to `typescript-mode` or `tsserver`.

## Relevant Version Numbers

- Tide: 3.6.2
- TypeScript:
- Emacs:26.3

(The list above is minimal. Make sure to include any other version numbers relevant to your report.)

## Steps to Reproduce the Bug
hi a vimer new come to emacs.
when choose the method, cant get parentheses.
like i select this method
![image](https://user-images.githubusercontent.com/41671631/65053253-40660a00-d99e-11e9-9414-6d53db37e6fc.png)
i get  `document.get`

## Expected Behavior

get `document.get(|)`

## Actual Behavior

cant get parentheses

**Comment by ananthakumaran** [comment] 2019-09-17 15:07
this is a duplicate of https://github.com/ananthakumaran/tide/issues/84

**Closed** 2019-09-17 15:08 UTC

**Comment by taigacute** [comment] 2020-01-31 10:34
@ananthakumaran  hi  any update for this issue?

**Comment by ananthakumaran** [comment] 2020-01-31 12:18
There was one attempt to fix the issue https://github.com/ananthakumaran/tide/pull/100. Check the comments for details.
