### ISSUE TITLE
Indent size not applied for (Emacs 29+ treesitter based) typescript-ts-mode

### ISSUE THREAD

**Issue by qst0528** [ananthakumaran/tide#474] opened 2024-10-19 16:51 UTC
When submitting issues to this project, please include the following information.

## Checklist

- [x] I have searched both open and closed issues and cannot find a duplicate.
- [x] I can [reproduce the problem](https://github.com/ananthakumaran/tide/wiki/Explanations-about-the-Issue-Reporting-Checklist#use-the-latest-version-of-the-relevant-packages) with the latest version of the relevant packages.
- [x] The problem still occurs after I issued [`M-x tide-restart-server`](https://github.com/ananthakumaran/tide/wiki/Explanations-about-the-Issue-Reporting-Checklist#try-m-x-tide-restart-server) in the buffer where I had the problem.
- [x] I verified that the version and the configuration file path reported by [`M-x tide-verify-setup`](https://github.com/ananthakumaran/tide/wiki/Explanations-about-the-Issue-Reporting-Checklist#check-the-information-reported-by-m-x-tide-verify-setup) are correct.
- [x] If [tide *is reporting*](https://github.com/ananthakumaran/tide/wiki/Explanations-about-the-Issue-Reporting-Checklist#the-behavior-of-cli-tools-agrees-with-your-expectations) an error or warning I think *should not be reported*, I can run `tsc` (and `tslint`, if applicable) without the error or warning I'm seeing in tide.
- [x] If [tide is *not reporting*](https://github.com/ananthakumaran/tide/wiki/Explanations-about-the-Issue-Reporting-Checklist#the-behavior-of-cli-tools-agrees-with-your-expectations) an error or warning I think *should be reported*, `tsc` (or `tslint`, if applicable) reports the error or warning I was expecting to see.
- [x] I am [positive](https://github.com/ananthakumaran/tide/wiki/Explanations-about-the-Issue-Reporting-Checklist#how-to-determine-which-project-the-problem-belongs-to) the problem does not belong to `typescript-mode` or `tsserver`.

## Relevant Version Numbers

- Tide: b38dfc3
- TypeScript: tsserver version 5.6.3
- Emacs: GNU Emacs 29.4 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.43, cairo version 1.18.2)

(The list above is minimal. Make sure to include any other version numbers relevant to your report.)

## Steps to Reproduce the Bug

Use new typescript-ts-mode instead of [typescript-mode](https://github.com/emacs-typescript/typescript.el) to open typescript file.  Indent size is set here.
https://github.com/ananthakumaran/tide/blob/b38dfc3f8fb754e64e48e76fc92d472cb3d1a3dc/tide.el#L935-L944

## Expected Behavior

`typescript-ts-mode-indent-offset` is set to indent

## Actual Behavior

The fallback `standard-indent` is set

**Comment by josteink** [comment] 2024-10-19 21:02
PR is merged. Feel free to close issue if you can verify things working as intended on latest revision !

**Closed** 2024-10-23 06:11 UTC
