### ISSUE TITLE
[[Feature Request]] Fill-In Function Arguments on Completion with Company-Mode

### ISSUE THREAD

**Issue by WammKD** [ananthakumaran/tide#376] opened 2020-05-06 16:50 UTC
If possible, I was wondering if we could get the feature to have Company mode fill in the arguments/parameters of a function it completes.

It's Java but these two screenshots should give the idea:

<img width="499" alt="Screen Shot 2020-05-06 at 11 32 38 AM" src="https://user-images.githubusercontent.com/10533934/81203415-8d2e3d80-8f8d-11ea-9523-238999283973.png">
<img width="338" alt="Screen Shot 2020-05-06 at 11 32 53 AM" src="https://user-images.githubusercontent.com/10533934/81203436-915a5b00-8f8d-11ea-81f9-659d54cc89c7.png">

The (hoped for) end result would be that the argument names (and, ideally, types) would be filled out between parentheses attached to the (now auto-completed) function name.

**Comment by josteink** [comment] 2020-05-23 11:35
I've seen this kind of completion in a few major-modes (although I can't remember which now), and honestly it has only annoyed me.

To cater to both kinds of audience, if this were to be implemented, I think it would be best for this to be a customizable behaviour.

**Comment by ananthakumaran** [comment] 2020-05-23 11:57
This is a duplicate of #84. see #100 for the previous attempt.

**Closed by ananthakumaran** 2020-05-23 11:57 UTC
