### ISSUE TITLE
Make tide-tsserver-executable use relative paths 

### ISSUE THREAD

**Issue by nahuel** [ananthakumaran/tide#59] opened 2016-09-06 16:06 UTC
If your TS projects always have `typescript` as an npm devDependency, then it will be nice to do:

`(setq tide-tsserver-executable "node_modules/typescript/bin/tsserver")	`

and make tide always use the local `tsserver` from each project.

**Comment by ananthakumaran** [comment] 2016-09-12 04:45
@nahuel I just test it locally, and relative path works fine for me. Tide starts different server for each project, so the config you have mentioned should work fine. I will clarify the documentation bit more. Let me know if you run into any issues.

**Comment by nahuel** [comment] 2016-09-14 23:07
Is not working for me, steps to reproduce the problem:

Emacs config:
```elisp
(setq tide-tsserver-executable "node_modules/typescript/bin/tsserver")	
```

Project creation:
```bash
mkdir /tmp/a
cd /tmp/a
npm init -y
npm install --save-dev typescript
./node_modules/typescript/bin/tsc -init
touch a.ts
```

Now open `/tmp/a/a.ts` in emacs, it shows:

```
(a) Starting tsserver...
File mode specification error: (file-error "Searching for program" "no such file or directory" "node_modules/typescript/bin/tsserver")
```
using tide-20160830.2120 the error shows when you open the file, using tide-20160911.2207 is showed when you save the file. Or use `M-x tide-restart-server` to show it

**Comment by ananthakumaran** [comment] 2016-09-15 03:51
I can't reproduce the problem. Maybe I have some config that adds the current `default-directory` to the `exec-path`?. Can you provide your emacs version?. I will try to analyze the problem.

**Comment by lzhoucs** [comment] 2016-09-25 03:59
I had the exact same issue when I tried to add `tide-tsserver-executable`. But when I tried adding `tide-tsserver-directory`, it worked!
```
 (setq tide-tsserver-directory "node_modules/typescript/lib")
```

**Comment by ananthakumaran** [comment] 2016-09-29 10:19
can you try master and see if this problem is fixed? I am expanding the file beforehand, so relative paths should be resolved correctly.

**Comment by nahuel** [comment] 2016-10-02 20:52
it seems to work ok with master! thanks @ananthakumaran! Just for future reference, I'm using:

```elisp
(setq tide-tsserver-executable "node_modules/typescript/bin/tsserver"
      tide-tsserver-directory  "node_modules/typescript/lib")
```

**Comment by ananthakumaran** [comment] 2016-10-03 04:00
Thanks, I will close this issue. Setting `tide-tsserver-directory` is not necessary if you set the value of `tide-tsserver-executable`.

**Closed by ananthakumaran** 2016-10-03 04:00 UTC
