### ISSUE TITLE
tide does not appear to parse tsconfig.app.json

### ISSUE THREAD

**Issue by jmcmichael** [ananthakumaran/tide#242] opened 2018-03-27 16:07 UTC
I'm using the nrwl/nx framework, which uses a monorepo to manage multiple angular apps. It maintains a [root tsconfig.json file](https://github.com/nrwl/nx-examples/blob/master/tsconfig.json), and individual [tsconfig.app.json](https://github.com/nrwl/nx-examples/blob/master/apps/demo/src/tsconfig.app.json) files that appear to inherit from the root tsconfig.

In order to use imports relative to the root of the application, I added a 'baseUrl' parameter to compilerOptions in tsconfig.app.json. The app subsequently compiles w/ the updated baseUrl, but tide complains that it cannot find imports relative to the baseUrl specified in the app tsconfig.

It appears like tide is only parsing the root tsconfig file, and not parsing/merging the app tsconfig.

Thank you for such a useful package, I am depending on it daily for my work.

**Comment by ananthakumaran** [comment] 2018-03-27 16:45
This is the first time I am hearing about tsconfig.app.json. I don't know how it's being used by other frameworks, but AFAIK, tsserver/tsc only respects tsconfig.json. This [comment](https://github.com/Microsoft/TypeScript/issues/21473#issuecomment-361998604) seems to confirm that. Let me know if I am missing something.

**Comment by jmcmichael** [comment] 2018-03-27 20:00
My first guess is that it is an angular-cli feature. I'm assuming that it merges tsconfig.json in the root of the project repo with the tsconfig.app.json at the root of the app folder, then compiles. However, I [wasn't able to find](https://github.com/angular/angular-cli/search?p=1&q=%22tsconfig.app.json%22&type=&utf8=%E2%9C%93) where it applies any magic as it calls the compiler. 

Microsoft's Typescript site [likewise doesn't appear to contain anything regarding tsconfig.app.json](https://www.google.com/search?client=firefox-b-1-ab&ei=bqK6WvDWBqKpjwTa7YPYDg&q=site%3Ahttps%3A%2F%2Fwww.typescriptlang.org+%22tsconfig.app.json%22&oq=site%3Ahttps%3A%2F%2Fwww.typescriptlang.org+%22tsconfig.app.json%22&gs_l=psy-ab.3...3608.5880.0.6246.4.3.1.0.0.0.90.182.3.3.0....0...1.1.64.psy-ab..0.0.0....0.SgAkRXA-QqA).

Weird.

**Comment by josteink** [comment] 2018-04-03 10:05
I guess it shouldn't be *too* hard to look for this file too, and I'm not against such a change.

Feel like submitting a PR @jmcmichael?

**Comment by ananthakumaran** [comment] 2018-04-03 10:12
@josteink it's not about tide, it's about tsserver. tsserver also has to respect the file, otherwise it will be operating at different context

**Comment by josteink** [comment] 2018-04-03 10:12
Yeah that's true. Not much we can do about it then?

**Comment by ananthakumaran** [comment] 2018-04-03 10:13
I haven't looked into the problem deeply, like what's angular-cli doing. But just adding the file to tide won't solve the issue for sure.

**Comment by lddubeau** [comment] 2018-07-30 20:15
I've recently tried angular-cli and I ran into this problem. Some thoughts:

1. As ananthakumaran mentioned, having tide identify `tsconfig.app.json` as the configuration file to use won't be enough. `tsserver` would also have to know that it must use that file. Assuming I'm reading the `tsserver` protocol correctly, there's a `projectFileName` argument that could be passed with the `open` command, which seems to be the way one would open a file with an arbitrary configuration. Though in practice I don't know whether a) it would give the expected results but b) without having undesirable side-effects.

2. Even if `projectFileName` can be used, it is not clear what rules tide should use to determine which configuration file applies. The problem is not merely that there is a configuration file with an unusual name, but that there are multiple configuration files which may apply. A typical project created with angular-cli will have `src/tsconfig.app.json` and `src/tsconfig.spec.json`. The former is for the app itself. The latter is for the test code. The test files and the application code are in the same file hierarchy. When opening `src/app/app.component.ts`, the configuration file to use is `src/tsconfig.app.json`. When opening `src/app/app.component.spec.ts`, the configuration file to use is `src/tsconfig.spec.json`. There's no way to tell which configuration file applies to which source file unless either a) angular-cli's conventions are coded in tide (yuck!!!, and this is ultimately brittle) or b) the JSON files are opened and interpreted to figure out whether a configuration file applies to a specific source file. (This means applying globbing patterns to figure out whether the source file is covered by the configuration file.)

3. Tide cannot *generally* just start looking at "`tsconfig`-like" files and use them because that would break some projects. I have some projects that use `tsconfig.something.json` for files that are then loaded through `extends`. It would be definitely wrong for tide to ever use those files directly.

4. If we start adding code to tide to handle angular-cli's peculiar naming conventions, where does it stop? Some other framework adds a bunch of other conventions, which then tide has to support, etc.

5. Maybe there's a good argument to be made for adding to tide a standard way to determine a value for `projectFileName` when tide asks `tsserver` to open a file. By default, it would remain unset (current behavior) but users who want to experiment would have a way to set whatever value they want, and deal with the consequences. Maybe this way someone could come up with a recipe for use by those who use angular-cli.

**Comment by josteink** [comment] 2018-08-01 06:49
Thanks for the detailed write-up, @lddubeau.

To me this sounds as messy as it gets, and I think it's an unreasonable burden to put this *core typescript infrastructure* matter to be resolved by a dozen independent third party developers just trying to integrate their editors with tsserver.

I really think the only way to do this proper, and to do this well, is if Microsoft and the Typescript-team provided an official way to resolve this, which they maintained, and which we can then plug into.

The Typescript-team has been lenient in the past w.r.t. ensuring good third-party interoperability. I can't see why they wouldn't be interested in trying to come up with a solution for this aspect as well.

Would anyone like to create and follow up an issue with Microsoft?

@jmcmichael: You were the one filing this issue in the first place. How about you? How about it? 😄

**Comment by jmcmichael** [comment] 2018-08-01 14:41
@josteink I would really like to contribute, however my main focus is UI design and this kind of work is a few layers deeper into the workflow stack than I feel comfortable venturing. Particularly when I'm still getting my head around Angular's ecosystem. I'll probably run into this problem again in the near future and will poke around for a solution, maybe run it by the nrwl/nx folks.

**Comment by mtuzinskiy** [comment] 2019-08-27 02:40
@lddubeau @jmcmichael  Did you guys eventually find any workaround for this?..

**Comment by vbraun** [comment] 2020-08-19 10:16
This is the new (with typescript 3.0) composite / project references feature. Editors shouldn't need to know about any special tsconfig.something.json; Instead the reference is set up in the tsconfig.json:
````
$ cat tsconfig.json 
{
    "files": [],
    "references": [
        {
            "path": "./tsconfig.something.json"
        }
    ]
}
````
and the referenced file has
````
$ cat tsconfig.something.json 
{
    "compilerOptions": {
        "declaration": false
    },
    "files": [
        "src/main.ts"
    ],
}
````
There can be multiple project references, but src/main.ts only has the typescript settings applied from tsconfig.something.json

**Comment by ananthakumaran** [comment] 2021-04-12 16:39
closing this as `references` seems to solve the issue.

**Closed by ananthakumaran** 2021-04-12 16:39 UTC
