### ISSUE TITLE
Parameter implicitly has any type, but a better type my be inferred from usage [7044]

### ISSUE THREAD

**Issue by ChoppinBlockParty** [ananthakumaran/tide#301] opened 2019-02-08 15:53 UTC
I am using tide for Javascript, no Typescript. I get this warning everywhere. For example,

    const SingleValue = ({ children, ...props }) => (
      <Typography
        {...props.innerProps} >
        {children}
      </Typography>
    )

`children` here will be marked as a warning. But in Javascript I cannot specify type, right? How can I disable this buzzing warnings?

**Comment by ananthakumaran** [comment] 2019-02-10 05:09
could you be more specific about what you expect? some screenshots would be useful. Btw, this issue tracker is mostly about bugs in tide emacs plugin. If it's a general question about tsc behaviour on javascript, it would be better suited for StackOverflow or other such mediums.

**Comment by ChoppinBlockParty** [comment] 2019-02-11 18:23
@ananthakumaran Yes, it is more a usage question then a bug. I think the 'tide' topic is not too active on SO, I thought it would be more helpful to have it here. I am looking for any ReactJS users of tide to help up, I am sure they have fixed that somehow in their workflow.

**Comment by ananthakumaran** [comment] 2019-06-16 07:24
I tried this sample, but couldn't reproduce the problem. You could specify types via jsdoc https://github.com/Microsoft/TypeScript/wiki/JSDoc-support-in-JavaScript

I am closing this because it's not a bug in tide. Feel free to reopen if that's the case.

**Closed by ananthakumaran** 2019-06-16 07:24 UTC
