### ISSUE TITLE
tide fix import statements with single quote

### ISSUE THREAD

**Issue by longitude** [ananthakumaran/tide#178] opened 2017-07-20 15:22 UTC
`tide-fix` currently adds missing imports with double quotes, is there a way to add imports with single quotes?

**Comment by josteink** [comment] 2017-07-20 20:43
tide just does whatever tsserver tells it to. 

My guess is that you'll have to alter your tsconfig.json file and your preferred formatting styles there and hopefully tsserver (and thus tide) may oblige.

**Comment by ananthakumaran** [comment] 2017-07-21 03:46
duplicate of #168

**Closed by ananthakumaran** 2017-07-21 03:46 UTC
