### ISSUE TITLE
tide--load-tsconfig-extension fails when using package

### ISSUE THREAD

**Issue by aaronjensen** [ananthakumaran/tide#310] opened 2019-04-03 13:08 UTC
When submitting issues to this project, please include the following information.

## Checklist

- [x] I have searched both open and closed issues and cannot find a duplicate.
- [x] I can [reproduce the problem](https://github.com/ananthakumaran/tide/wiki/Explanations-about-the-Issue-Reporting-Checklist#use-the-latest-version-of-the-relevant-packages) with the latest version of the relevant packages.
- [x] The problem still occurs after I issued [`M-x tide-restart-server`](https://github.com/ananthakumaran/tide/wiki/Explanations-about-the-Issue-Reporting-Checklist#try-m-x-tide-restart-server) in the buffer where I had the problem.
- [x] I verified that the version and the configuration file path reported by [`M-x tide-verify-setup`](https://github.com/ananthakumaran/tide/wiki/Explanations-about-the-Issue-Reporting-Checklist#check-the-information-reported-by-m-x-tide-verify-setup) are correct.
- [x] If [tide *is reporting*](https://github.com/ananthakumaran/tide/wiki/Explanations-about-the-Issue-Reporting-Checklist#the-behavior-of-cli-tools-agrees-with-your-expectations) an error or warning I think *should not be reported*, I can run `tsc` (and `tslint`, if applicable) without the error or warning I'm seeing in tide.
- [x] If [tide is *not reporting*](https://github.com/ananthakumaran/tide/wiki/Explanations-about-the-Issue-Reporting-Checklist#the-behavior-of-cli-tools-agrees-with-your-expectations) an error or warning I think *should be reported*, `tsc` (or `tslint`, if applicable) reports the error or warning I was expecting to see.
- [x] I am [positive](https://github.com/ananthakumaran/tide/wiki/Explanations-about-the-Issue-Reporting-Checklist#how-to-determine-which-project-the-problem-belongs-to) the problem does not belong to `typescript-mode` or `tsserver`.

## Relevant Version Numbers

- Tide: `20190321.1611`
- TypeScript: `3.4.1`
- Emacs: `GNU Emacs 27.0.50 (build 1, x86_64-apple-darwin18.2.0, NS appkit-1671.20 Version 10.14.3 (Build 18D109)) of 2019-03-20`

(The list above is minimal. Make sure to include any other version numbers relevant to your report.)

## Steps to Reproduce the Bug

See https://github.com/aaronjensen/tide-extends-repro

## Expected Behavior

tide would support extends taking a package name + path

## Actual Behavior

tide does not

**Comment by lddubeau** [comment] 2019-04-03 13:38
Thank you for using the issue template. I took a quick look and discovered the following:

* Prior to TypeScript 3.2 the setup shown in the reproduction case was not supported by TypeScript.

* What's going on is that yarn creates `node_modules/base` and `node_modules/sub` which are links:

   ```
   $ ls -l node_modules/
   total 4
   lrwxrwxrwx 1 ldd ldd    7 Apr  3 09:25 base -> ../base
   lrwxrwxrwx 1 ldd ldd    6 Apr  3 09:25 sub -> ../sub
   drwxr-xr-x 4 ldd ldd 4096 Apr  3 09:25 typescript
   ```

   The file `sub/tsconfig.json` uses `extends: "base/tsconfig"` and the file resolution from 3.2 onwards treats a non-relative and non-absolute path in a way similar to Node's module path. (This is a rough description. I don't know the details. And note that paths that were not relative or absolute were just not allowed prior to tsc 3.2.) So, relative to the top directory of the project, it resolves to `./node_modules/base/tsconfig.json` and once the symlink is resolved, that's `./base/tsconfig.json`.

It is a real bug due to a change in how TypeScript handles paths in `extends`.

PRs welcome.

**Comment by zhenwenc** [comment] 2019-05-02 22:42
I suspect `tide` no longer need to reimplement the logic of resolving `tsconfig.json` files, but use `tsc --showConfig` commands which was introduced in TS 3.2.

Here is an example (not a solution):
```
(defun zc/tide-load-tsconfig (path &rest _ignored)
  "Overrides `tide-load-tsconfig'."
  (when (not (file-exists-p path))
    (error "tsconfig file not found at %S." path))
  (condition-case nil
      (let ((json-object-type 'plist)
            (json (shell-command-to-string "tsc --showConfig")))
        (json-read-from-string json))
    (error '())))

(advice-add 'tide-load-tsconfig :override #'zc/tide-load-tsconfig)

```

**Comment by ananthakumaran** [comment] 2019-06-08 10:05
have anybody tested https://github.com/ananthakumaran/tide/pull/317? we could consider merging it if it fixes the problem

**Comment by zhenwenc** [comment] 2019-06-08 11:02
My 2 cents, the operation looks kinda heavy (many file system traversing).

I am wondering what was the reason of not using `tsc --showConfig`? Is it to support JS devs without having TypeScript installed? 

If that's the case, can we just test whether the existence of `tsc` executable, if exists then use `--showConfig`, otherwise throw an error (most likely JS project doesn't have `tsconfig.json` file)?

**Comment by ananthakumaran** [comment] 2019-06-08 11:10
The downside is the added dependency on `tsc`. But yes, given that this logic is getting complicated, I would be ok with using tsc and if not available, just log a warning and move on. We use the config only for `compileOnSaveEmitFile` command, which is likely not critical compared to other functionalities. PRs are welcome.

**Closed** 2019-06-14 12:27 UTC
Labels: bug
