### ISSUE TITLE
this jsconfig.json file make tide slow and high cpu useage

### ISSUE THREAD

**Issue by yadex** [ananthakumaran/tide#365] opened 2020-02-28 10:59 UTC
``` json
{
  "compilerOptions": {
    "target": "es2017",
    "allowSyntheticDefaultImports": true,
    "noEmit": true,
    "checkJs": true,
    "jsx": "react",
    "lib": [ "dom", "es2017" ]
  }
}
```

**Comment by josteink** [comment] 2020-02-28 11:12
Hey @yadex.

Thanks for your report. I'm not sure if this is a tide-error or not.

At least without evidence to prove it so, I would instead assume this is an problem with `tsserver` from Typescript which is used by `tide` underneath the hood.

You can check this yourself:

* Can you reproduce this same issue in VSCode? If so, it's more likely a issue with `tsserver`.
* Is Emacs CPU-usage high or does the `tsserver` process use  lots of CPU? If the `tsserver` process is busy, it will be slow to respond to `tide` and there's nothing `tide` can do about that.

Let me know what you find out!

**Comment by lddubeau** [comment] 2020-02-28 18:58
The OP filled a report about the same problem with [`coc-tsserver`](https://github.com/neoclide/coc-tsserver/issues/119) which is a `vim` plugin. The fact that the same problem occurs there too is **very strong evidence that the problem is not `tide` but `tsserver`.** I'm going to close this. We can reopen if it can be shown that `tide` has any part in this issue.

**Closed by lddubeau** 2020-02-28 18:58 UTC
